# In _config.yml
title: Computational Chemistry Notes
author: Richard Van
# logo: logo.png
execute:
  execute_notebooks: force
launch_buttons:
  colab_url: "https://colab.research.google.com"

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

name: CodingNotes
# Only run this when the master branch changes
on:
  push:
    branches:
    - master
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    paths:
    - notebooks/**

# Information about where the book exists on the web
repository:
  url                       : https://github.com/van-richard/CodingNotes  # Online location of your book
  path_to_book              : notebooks/ # Optional path to your book, relative to the repository root
  branch                    : gh-pages  # Which branch of the repository should be used when creating links (optional)

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
