 # In _config.yml
title: Coding Notes
author: Richard Van
copyright: "2023"
logo: "_static/images/logo2.png"
exclude_patterns: ["README.md", "drafts", "assets", "assets/*", "linuxlist.sh", "build.sh"]

execute:
  execute_notebooks: cache

html:
  baseurl: https://van-richard.github.io/CodingNotes
  use_repository_button: false
  use_edit_page_button: false 
  html_static_path: ["_static/"]
  home_page_in_navbar: false
  

repository:
  url: https://github.com/van-richard/CodingNotes
  branch: main

   
parse:
  myst_enable_extensions:  
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true

sphinx: 
  extra_extensions:
    - sphinx_tippy
    - sphinx_design
    - sphinxcontrib.mermaid
    - sphinx_proof
  config: 
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib


