# In _config.yml
title: Coding Notes
author: Richard Van
logo: _static/logo.png
execute:
  execute_notebooks: force
repository:
  url: https://github.com/van-richard/CodingNotes

# Auto-exclude files not in the toc
# only_build_toc_files        : true
exclude_patterns: ['README.md', 'drafts', 'assets', 'linuxlist.sh', 'build.sh']

html:
  use_repository_button: true
  use_edit_page_button: true
  use_multitoc_numbering: false
    
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true

sphinx: 
  extra_extensions:
    - sphinx_design
    - sphinxcontrib.mermaid
    - sphinx_proof
  config: 
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

name: CodingNotes
# Only run this when the master branch changes
on:
  push:
    branches:
    - master
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    paths:
    - notebooks/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
